### ISSUE TITLE
vjoy falure on windows 19H1

### ISSUE THREAD

**Issue by Dal78** [nlp80/irFFB#19]
Vjoy is not working on windows 10 version 19H1.

I have tried re-installing but it fails on re-install.

**Comment by bramhaag** [comment]
This is an issue with vJoy. Sadly vJoy is no longer supported by its original author so there won't be an official update. The community is working on an update, see https://vjoy.freeforums.net/thread/101/windows-1903-install-vjoy. For now, you can use the unsigned release found [here](https://github.com/R-T-B/vJoy/releases), but you'll need to put your PC in test mode to install it.

**Comment by slikk66** [comment]
hi, first time irFFB user, have been following the vjoy situation for a couple weeks now.  I've installed the new "working" vjoy that has been signed for windows10 (https://github.com/jshafer817/vJoy/releases/tag/v2.1.9.1) and although it seems to install fine, I get an error on irFFB saying "vJoy driver version 0219 != required version 0218!" and the direct modes don't seem to be working, I get no ffb in iracing with direct modes.  I've tried recalibrating as many people suggest that, but no feedback.

Am I doing something wrong? or will irFFB not work either until it accepts 219 as a valid version as well?

Thanks!

**Comment by slikk66** [comment]
can confirm that the check is blocking the new version 2.1.9.1 from working on the latest irFFB, I was able to remove the check and build a test exe where now it works.  It's here if anyone wants it, but since I don't know how to properly do the check, I just disabled it.. so wait for these guys here to fix it for real: https://github.com/slikk66/irFFB/releases/tag/v6.2.1

**Comment by KSNelson300** [comment]
well vjoy updated other day. so that fixed that issue I was having due to window 10.  but now the irffb says vjoy wrong driver version.  it sees the new vjoy but thinks it isto new for irffb now.  any chance we can get irffb to update its ability to use new version of vjoy 2.1.9.1. says needs 0218 version but 0219 version vjoy drivers installed

**Comment by samkatakouzinosracing** [comment]
@KSNelson300 clearly you've not read the thread that you attached your comment to.
Read the last message before yours by @slikk66 .

**Comment by adampatarino** [comment]
@slikk66 fix works for me.

+1 to merge PR

**Comment by nlp80** [comment]
Fixed in https://github.com/nlp80/irFFB/commit/02e73b95860d1c86a5d904a8073dc383ebcfbf91: Version check will not allow any version >= the 'dll' version,
